title: 'Penn Artificial Intelligence and Technology Collaboratory for Healthy Aging: Tech Core'
description: 'Tech ID from literature via text mining & expert curation'
theme: just-the-docs

url: https://syang11.github.io/pennAITech/

aux_links:
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template
  PennAITech: https://www.pennaitech.org/
