title: PennAITech core #'Penn Artificial Intelligence and Technology Collaboratory for Healthy Aging: Tech Core'
description: 'Penn Artificial Intelligence and Technology Collaboratory for Healthy Aging: Tech Core'  #'Tech ID from literature via text mining & expert curation'
theme: just-the-docs

url: https://syang11.github.io/pennAITech/

aux_links:
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template
  PennAITech: https://www.pennaitech.org/

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# -------- below follows from PennLINC (https://pennlinc.github.io/): https://github.com/PennLINC/PennLINC.github.io/blob/main/_config.yml
permalink: pretty

exclude:
 # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
 # specific to the theme website:
   - bin/
   - lib/
   - "*.gemspec"
   - "*.gem"
   - LICENSE.txt
   - package.json
   - package-lock.json
   - Rakefile
   - README.md
   - CODE_OF_CONDUCT.md
   - docker-compose.yml
   - Dockerfile
 # theme test code
   - fixtures/

# Footer content
# appears at the bottom of every page's main content
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2017-2019 Patrick Marsceill. Distributed by an <a href=\"https://https://github.com/syang11/pennAITech/tree/main/LICENSE\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
#  -------